#!/usr/bin/env bash
#Usage: clone-database source_db_host source_db_user source_db_name dest_db_host dest_db_user dest_db_name
set -x

source_db_host=$1
source_db_user=$2
source_db_name=$3
dest_db_host=$4
dest_db_user=$5
dest_db_name=$6

echo "Starting cloning"
pg_dump -v -U ${source_db_user} -h ${source_db_host} ${source_db_name} | psql -h ${dest_db_host} -U ${dest_db_user} ${dest_db_name}

